source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

abstract_target 'import_pods' do
    pod 'AMOrientationUpdatingImageView', :path => '../'

    target 'AMOrientationUpdatingImageView_Example' do
end

    target 'AMOrientationUpdatingImageView_Tests' do
        pod 'Nimble', '~> 7.0'
    end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_TESTABILITY'] = 'YES'
    end
  end
end
