source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AMOrientationUpdatingImageView_Example', :exclusive => true do
  pod "AMOrientationUpdatingImageView", :path => "../"
end

target 'AMOrientationUpdatingImageView_Tests', :exclusive => true do
  pod "AMOrientationUpdatingImageView", :path => "../"

  pod 'Nimble', '2.0.0-rc.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_TESTABILITY'] = 'YES'
    end
  end
end